export enum RouteKey {
  _ = '../',
  empty = '',
  home = 'home',
  r = 'r',
  pool = 'pool',
  pools = 'pools',
  poolsPublic = 'pools/public',
  poolsPrivate = 'pools/private',
  sub_PoolsPrivate = 'private',
  sub_PoolsPublic = 'public',

  trade = 'trade',
  broker = 'trade/broker',
  vault = 'vault',
  vaultStDetail = 'vault/detail',
  sld = 'sld',
  mining = 'mining',
  vote = 'vote',
  referral = 'referral',
  sub_ReferralDetail = 'detail',
  poster = 'poster',

  claim = 'claim',
  union = 'union',

  stake = 'stake',
  stoneEco = 'stone-eco',
  rewards = 'rewards',
  gNft = 'g-nft',
  gauge = 'gauge',
  portfolio = 'portfolio-allocation',
  portfolioVoteList = 'vote-list',
  portfolioVoteDetail = 'vote-detail',
  bridge = 'bridge',
}
